config/routes.rb
Rails.application.routes.draw do
  post 'messages/create',   to: 'messages#create'
  get  'messages/show/:id', to: 'messages#show'

  get 'tickets/search', to: 'tickets#search'

  get  'access',          to: 'access#login'
  get  'access/sign_up',  to: 'access#sign_up'
  post 'access/sign_up',  to: 'access#create'
  get  'access/index',    to: 'access#login'
  get  'access/login',    to: 'access#login'
  get  'access/logout',   to: 'access#logout'
  post 'access/attempt',  to: 'access#attempt'

  get  'history', to: 'tickets#history_index'
  post 'history', to: 'tickets#history_show'

  get  'submit', to: 'tickets#submit_index'
  post 'submit', to: 'tickets#submit_create'

  get 'intro', to: 'intro#index'

  post 'chat/auth', to: 'chat#auth'

  root to: 'intro#index'

  resources :tickets
  resources :users

end

app/controllers/intro_controller.rb
class IntroController < ActionController::Base
  # GET /
  # GET /intro
  def index
    # instructions on how to use the application
  end
end

app/views/intro/index.html.erb
<h2 class="text-center">Hi!</h2>
<p class="text-center mute">Thank you <strong>very</strong> much for helping me out with my dissertation.</p>

<div class="text-justify">
  <p>My name is Mario and I am pursuing a MSc. in Information Systems with Computing at the <%= link_to 'Dublin Business School', 'http://dbs.ie' %> in Ireland. I am using this site as a tool to research the effect that hybrid support systems have in customer experience and satisfaction — and in this case, <strong>you</strong> are the customer, and I need you to help me out!</p>

  <p>This will only take a few minutes of your time and you'll make someone you don't know very happy. Consider this your good deed of the day.</p>

  <h4>Instructions</h4>
  <ol>
    <li><%= link_to 'Submit a new ticket here', submit_path %> with anything you can think of.
      <ul>
        <li>It can be a simple request, a question about literally <em>anything</em>, or just casual conversation. Just
          be sure you use a valid email address so you can get notifications.
        </li>
      </ul>
    </li>

    <li><%= link_to 'Check your ticket', history_path %> and add anything else you'd like there.
      <ul>
        <li>It's good to know that everything was saved correctly and to learn how to check how the conversation's going.</li>
      </ul>
    </li>

    <li>Wait for me to get back to you, then let the conversation begin!
      <ul>
        <li>You will receive further instructions in my replies on how to use the live chat (if I am available) or the regular system. It's a couple of clicks tops!</li>
      </ul>
    </li>

    <li><a href="https://aerocross.typeform.com/to/UG8hqA">Fill the survey</a> after the conversation is over so I can get your feedback.</li>

  </ol>

  <p><strong>That's it!</strong> Thank you very much — and if I may say, your hair looks epic today and you smell like a meadow.</p>

  <hr />

  <a id="show-more-info">More information about the project</a>

  <div id="more-info" class="hidden">
    <h5>Info for the very interested</h5>

    <ul>
      <li>You can submit as many tickets as you like and I'll be happy to respond.</li>
      <li>If you want access to the <%= link_to 'entire application', tickets_path %> so you can check your history, add new tickets, and such, you can <%= link_to 'create an account', access_sign_up_path %>. All your previous open tickets will show up there.</li>
      <li>Don't store there anything you want to remember. The data will be purged. Frequently.</li>
      <li>Your email will not be used for anything other than notifications.</li>
      <li>Everything in this study (including the survey) is completely anonymous and the data that's stored in the servers will be deleted shortly after the study is complete.</li>
      <li>You can contact me personally through <code>10121029 at mydbs dot ie</code> if you want the information removed from the servers before this happens or have any questions about the research.</li>
      <li>The code is completely open-source and can be found on <%= link_to 'GitHub', 'http://github.com/AeroCross/relay-async' %>.</li>
      <li>The code is <strong>not production ready</strong>, so don't attempt to use it in live environments unless you want to fork it and make something awesome.</li>
    </ul>

    <h5>Tools</h5>

    <ul>
      <li><a href="https://www.ruby-lang.org/en/">Ruby 2.2.2</a></li>
      <li><a href="http://rubyonrails.org/">Rails 4.2</a></li>
      <li><a href="http://dev.mysql.com/">MySQL 5.5</a></li>
      <li><a href="https://github.com/stympy/faker">Faker</a></li>
      <li><a href="https://github.com/laserlemon/figaro">Figaro</a></li>
      <li><a href="http://getbootstrap.com/">Bootstrap</a></li>
      <li><a href="https://bootswatch.com/">Bootswatch Rails + Paper</a></li>
      <li><a href="http://unicorn.bogomips.org/">Unicorn</a></li>
      <li><a href="http://nginx.org/">nginx</a></li>
      <li><a href="http://nodejs.org/">Node.js</a></li>
      <li><a href="http://express-io.org/">Express.io</a></li>
      <li><a href="http://socket.io/">Socket.io</a></li>
    </ul>

    <h5>Credits</h5>

    <ul>
      <li>Ruby / Rails code written by <a href="http://mariocuba.net">Mario Cuba</a></li>
      <li>Node.js code is a modified version of <a href="http://tutorialzine.com/2014/03/nodejs-private-webchat/">this Tutorialzine app</a> to fit the needs of the research.</li>
      <li>All other code belongs to their respective authors, as linked, unless otherwise noted.</li>
    </ul>
  </div>

</div>