config/routes.rb
Rails.application.routes.draw do
  post 'messages/create',   to: 'messages#create'
  get  'messages/show/:id', to: 'messages#show'

  get 'tickets/search', to: 'tickets#search'

  get  'access',          to: 'access#login'
  get  'access/sign_up',  to: 'access#sign_up'
  post 'access/sign_up',  to: 'access#create'
  get  'access/index',    to: 'access#login'
  get  'access/login',    to: 'access#login'
  get  'access/logout',   to: 'access#logout'
  post 'access/attempt',  to: 'access#attempt'

  get  'history', to: 'tickets#history_index'
  post 'history', to: 'tickets#history_show'

  get  'submit', to: 'tickets#submit_index'
  post 'submit', to: 'tickets#submit_create'

  get 'intro', to: 'intro#index'

  post 'chat/auth', to: 'chat#auth'

  root to: 'intro#index'

  resources :tickets
  resources :users

end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  belongs_to :user
  has_many :messages
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  require "#{Rails.root}/lib/utilities"

  before_action :confirm_login, except: [:history_index, :history_show, :submit_index, :submit_create]
  before_action :set_ticket, only: [:show, :edit, :update, :destroy]

  layout :resolve_layout

  # prevent regular users from messing with stuff
  before_action only: [:show, :edit, :update, :destroy] do
    restrict_access(@ticket.user.id)
  end

  # GET /tickets
  # GET /tickets.json
  def index
    # @TODO: have a "show all" setting
    @tickets = Ticket.includes(:user).all
  end

  # GET /tickets/search
  def search
    redirect_to action: 'show', id: params[:id]
  end

  # GET /tickets/1
  # GET /tickets/1.json
  def show
    @messages = Message.includes(:user).where(ticket_id: params[:id]).order(created_at: :desc)
  end

  # GET /tickets/new
  def new
    @ticket = Ticket.new
  end

  # GET /tickets/1/edit
  def edit
  end

  # POST /tickets
  # POST /tickets.json
  def create
    @ticket = Ticket.new(ticket_params)
    @ticket.auth_admin = random_string(20).upcase
    @ticket.auth_client = random_string.upcase

    respond_to do |format|
      if @ticket.save

        # temporary
        if Rails.application.config.async.notify_all_emails
          TicketMailer.new_ticket(@ticket, Rails.application.config.async.notify_to).deliver_now
        end

        format.html { redirect_to @ticket, notice: 'Ticket was successfully created.', flash: {type: 'success'} }
        format.json { render :show, status: :created, location: @ticket }
      else
        format.html { render :new }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tickets/1
  # PATCH/PUT /tickets/1.json
  def update
    respond_to do |format|
      if @ticket.update(ticket_params)
        format.html { redirect_to @ticket, notice: 'Ticket was successfully updated.', flash: {type: 'info'} }
        format.json { render :show, status: :ok, location: @ticket }
      else
        format.html { render :edit }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tickets/1
  # DELETE /tickets/1.json
  def destroy
    @ticket.destroy
    respond_to do |format|
      format.html { redirect_to tickets_url, notice: 'Ticket was successfully destroyed.', flash: {type: 'warning'} }
      format.json { head :no_content }
    end
  end

  # GET /history
  def history_index
    # form asking for creator email and ticket id, which will be sent through an email
  end

  # POST /history
  def history_show
    begin
      # check if the ticket exists first
      @ticket = Ticket.includes(:user, :messages).find(params[:ticket_id])
      @messages = @ticket.messages.order('created_at DESC')

      # then if the email matches the ticket
      if params[:email] != @ticket.user.email
        raise ActiveRecord::RecordNotFound
      end
    rescue
      # @TODO: refactor: render, dog! render!
      redirect_to history_path, flash: {notice: 'We couldn\'t find a ticket with that information. Make sure you check your email for the right information.', type: 'warning text-center'}
    end
  end

  # GET /submit
  def submit_index

  end

  # POST /submit
  def submit_create
    # 1. check if the email doesn't exists so it can create a new blank user
    @user = User.where({email: params[:email]}).first

    if @user.nil?
      @user = User.new
      @user.public = true
      @user.email = params[:email]
      @user.password = random_string(30)
      @user.fullname = nil
      @user.role = 'normal'
      @user.verified = 'no'
      @user.save
    end

    # 2. create the ticket
    @ticket = Ticket.new
    @ticket.subject = params[:subject]
    @ticket.content = params[:content]
    @ticket.user_id = @user.id
    @ticket.auth_client = random_string.upcase
    @ticket.auth_admin = random_string(20).upcase
    @ticket.save

    # 3. mail the user
    # temporary
    if Rails.application.config.async.notify_all_emails
      TicketMailer.new_ticket(@ticket, Rails.application.config.async.notify_to).deliver_now
    end

    TicketMailer.new_ticket(@ticket, @user.email).deliver_now

    # 4. redirect to the same screen with a success message
    if @ticket
      flash.now[:notice] = "Thanks! Your ticket is <strong>##{@ticket.id}</strong> and you should receive a reply shortly.".html_safe
      flash.now[:type] = 'success'
      render({file: 'tickets/submit_index', layout: 'history'})
    else
      flash.now[:notice] = 'Whoops! There was an error in your request. We\'ll have it fixed.'
      flash.now[:type] = 'error'
      render({file: 'tickets/submit_index', layout: 'history'})
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ticket
      @ticket = Ticket.includes(:user, :messages).find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ticket_params
      params.require(:ticket).permit(:user_id, :subject, :content, :status)
    end

    # Helper method to determine which layout should be used
    def resolve_layout
      case action_name
        when 'history_index', 'history_show', 'submit_index'
          'history'
        else
          'application'
      end
    end
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/tickets/_form.html.erb
<%= form_for(@ticket) do |f| %>
  <% if @ticket.errors.any? %>
    <div class="alert alert-warning">
      <strong><%= @ticket.errors.count > 1 ? 'A few errors have' : 'An error has' %> occurred:</strong>

      <ul>
      <% @ticket.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="form-group">
        <%= f.label :subject %><br>
        <%= f.text_area :subject, {:class => 'form-control'} %>
    </div>
    <div class="form-group">
        <%= f.label :content %><br>
        <%= f.text_area :content, {:class => 'form-control'}%>
    </div>

    <% if action_name == 'new' %>
        <!-- this prevent the form overriding the user creator when editing -->
        <%= f.hidden_field :user_id, {:class => 'form-control', value: session[:id]} %>

    <% end %>

    <div class="actions">
      <%= f.submit({:class => 'btn btn-primary'}) %>
    </div>

<% end %>

app/views/tickets/edit.html.erb
<%= render 'form' %>

<br />

<div class="btn-group">
  <a href="<%= url_for(@ticket) %>" class="btn btn-default">Show</a>
  <a href="<%= url_for(tickets_path) %>" class="btn btn-default">Back</a>
</div>

app/views/tickets/history_index.html.erb
<div class="text-center">
  <h3>View your ticket history</h3>
  <p>We'll get all the information you need in a hearbeat.</p>
</div>

<%= form_tag '/history' do %>
    <div class="form-group">
      <%= label_tag :email, 'Email address' %>
      <%= text_field_tag :email, nil, placeholder: 'Your email', class: 'form-control' %>
      <p class="help-block">Be sure to use the email you used when you first contacted us.</p>
    </div>

    <div class="form-group">
      <%= label_tag :ticket_id, 'Ticket ID' %>
      <%= text_field_tag :ticket_id, nil, placeholder: 'ID number', class: 'form-control' %>
      <p class="help-block">e.g <strong>7291</strong> — this can be found in the message you received when you contacted us.</p>
    </div>

    <%= button_tag 'Send', class: 'btn btn-primary pull-right' %>
<% end %>

app/views/tickets/history_show.html.erb
<!-- ticket -->
<div class="row">
  <div class="col-lg-12">

    <!-- initial ticket information -->
    <h4><%= @ticket.subject %></h4>
    <p><%= @ticket.content %></p>

    <!-- date data -->
    <p class="text-muted">
      <small>
        Submitted on
        <strong><%= @ticket.created_at.strftime '%A, %B %d, %Y at %I:%M:%S%P' %></strong> by
        <strong><%= @ticket.user.email %></strong>
      </small>
    </p>

    <p><strong>Status:</strong> <span class="label label-<%= @ticket.status == 'open' ? 'warning' : 'success' %>"><%= @ticket.status.capitalize %></span></p>

    <!-- reply form -->
    <%= form_tag '/messages/create' do |f| %>
        <div class="form-group">
            <%= label_tag 'message[content]', 'Send a reply' %>
            <%= text_area_tag 'message[content]', nil, class: 'form-control', 'rows': 7 %>
            <%= hidden_field_tag 'message[user_id]', @ticket.user.id %>
            <%= hidden_field_tag 'message[ticket_id]', @ticket.id %>
            <%= hidden_field_tag 'message[source]', 'ticket' %>
            <%= hidden_field_tag 'referrer', '/history/show' %>
        </div>

        <%= link_to 'Start a live chat', Rails.application.config.sync.root + '/chat/' + @ticket.id.to_s + '?email=' + @ticket.user.email + '&auth=' + @ticket.auth_client, class: 'pull-left' %>
        <%= button_tag 'Send', class: 'btn btn-primary pull-right' %>
    <% end %>
  </div>
</div>

<!-- chat log-->
<div class="history">
  <% unless @messages.blank? %>
      
      <h5>Previous messages</h5>
      <hr />

    <% @messages.each do |message| %>
        <div class="row">
          <% if message.source == 'chat' %>

              <div class="col-lg-12">
                <blockquote>
                  <strong><%= message.user.email %></strong>

                  <% if message.user.role == 'admin' %>
                      <span class="label label-success">Admin</span>
                  <% end %>

                  (<%= message.created_at %>):
                  <%= simple_format message.content %>
                </blockquote>
              </div>

          <% else %>

              <div class="col-lg-12">
                <div class="panel panel-default">
                  <div class="panel-heading">
                    <strong><%= message.user.email %></strong>
                    <small><%= message.created_at %></small>

                    <% if message.user.role == 'admin' %>
                        <span class="label label-success">Admin</span>
                    <% end %>

                  </div>

                  <div class="panel-body">
                    <p><%= simple_format message.content %></p>
                  </div>
                </div>
              </div>

          <% end %>
        </div>
    <% end %>
  <% end %>
</div>

app/views/tickets/index.html.erb
<% unless notice.blank? %>
    <div class="alert alert-<%= flash[:type].present? ? flash[:type] : 'info' %>">
      <%= notice %>
    </div>
<% end %>

<div class="row">
  <div class="col-lg-12">

    <table class="table table-striped table-bordered table-hover table-responsive tickets-table">
      <thead>
      <tr>
        <th>User</th>
        <th>Subject</th>
        <th>Content</th>
        <th>Created</th>
        <th colspan="3">Actions</th>
      </tr>
      </thead>

      <tbody>
      <% @tickets.each do |ticket| %>
        <% if ticket.status == 'open' %>
            <%
               # if not an admin, then show only tickets created by this user
               #
               # refactor: check the session in the controller and fetch
               # the required rows instead of omitting records
               if session[:role] != 'admin' && ticket.user.id != session[:id]
                next
               else
            %>

              <tr>
                <td><%= link_to ticket.user.email, edit_user_path(ticket.user.id) %></td>
                <td><%= link_to ticket.subject, ticket_path(ticket.id) %></td>
                <td><%= ticket.content %></td>
                <td class="text-nowrap"><%= ticket.created_at %></td>
                <td><%= link_to 'Show', ticket %></td>
                <td><%= link_to 'Edit', edit_ticket_path(ticket) %></td>
                <td><%= link_to 'Destroy', ticket, method: :delete, data: {confirm: 'Are you sure?'} %></td>
              </tr>

            <% end %>
        <% end %>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/tickets/new.html.erb
<%= render 'form' %>

app/views/tickets/show.html.erb
<% unless notice.blank? %>
    <div class="alert alert-<%= flash[:type].present? ? flash[:type] : 'info' %>">
      <%= notice %>
    </div>
<% end %>

<!-- message information -->
<div class="row">
  <div class="col-lg-10">
    <p>
      <strong>From:</strong>
      <%= @ticket.user.email %>
    </p>

    <p>
      <strong>Subject:</strong>
      <%= @ticket.subject %>
    </p>

    <p>
      <strong>Content:</strong>
      <%= @ticket.content %>
    </p>

    <p>
      <strong>Status:</strong>
      
      <span class="label label-<%= @ticket.status == 'open' ? 'warning' : 'success' %>">
        <%=  @ticket.status.capitalize %>
      </span>
    </p>

    <%= form_for @ticket do |f| %>
        <div class="btn-group">
          <a href="<%= url_for(edit_ticket_path) %>" class="btn btn-default">Edit</a>
          <%= f.button 'Open', name: 'ticket[status]', value: 'open', class: 'btn btn-default' %>
          <%= f.button 'Close', name: 'ticket[status]', value: 'closed', class: 'btn btn-primary' %>
        </div>
    <% end %>
  </div>

  <!-- auth codes -->
  <div class="col-lg-2">
    <div class="panel panel-info">
      <div class="panel-heading"><p class="panel-title">Live chat options</p></div>
      <div class="panel-body">
        <% if session[:role] == 'admin' %>
            <p><%= link_to 'Chat as Admin', Rails.configuration.sync.root + '/chat/' + params[:id] + '?email=' + session[:email] + '&auth=' + @ticket.auth_admin %></p>
            <p><strong>Admin auth code:</strong><br /> <%= @ticket.auth_admin %></p>
        <% end %>

        <p><%= link_to 'Chat as Customer', Rails.configuration.sync.root + '/chat/' + params[:id] + '?email=' + @ticket.user.email + '&auth=' + @ticket.auth_client %></p>
        <p><strong>Client auth code:</strong><br /> <%= @ticket.auth_client %></p>
      </div>
    </div>
  </div>
</div>

<!-- message reply -->
<div class="row top-buffer">
  <div class="col-lg-4">
    <%= form_for :message, url: messages_create_url do |f| %>
        <div class="form-group">
          <%= f.text_area :content, {placeholder: 'Send a reply', class: 'form-control', rows: 5} %>
        </div>

        <%= f.hidden_field :source, {value: 'ticket'} %>
        <%= f.hidden_field :user_id, {value: session[:id]} %>
        <%= f.hidden_field :ticket_id, {value: params[:id]} %>

        <div class="form-group">
          <%= f.submit('Reply', {class: 'btn btn-primary'}) %>
        </div>
    <% end %>
  </div>
</div>

<!-- messages -->
<% @messages.each do |message| %>
    <div class="row history">
      <% if message.source == 'chat' %>

          <div class="col-lg-12">
            <blockquote>
              <strong>
                <%= message.user.email %>
              </strong>

              <% if message.user.role == 'admin' %>
                  <span class="label label-success">Admin</span>
              <% end %>

              (<%= message.created_at %>):
              <%= simple_format message.content %>
            </blockquote>
          </div>

      <% else %>

          <div class="col-lg-12">
            <div class="panel panel-default">
              <div class="panel-heading">
                <strong><%= message.user.email %></strong>
                <small><%= message.created_at %></small>
              </div>

              <div class="panel-body">
                <p><%= simple_format message.content %></p>
              </div>
            </div>
          </div>

      <% end %>
    </div>
<% end %>

app/views/tickets/submit_index.html.erb
<div class="text-center">
  <h3>Get in touch.</h3>
  <p>We'll get back to you as soon as possible.</p>
</div>

<%= form_tag '/submit' do %>
    <div class="form-group">
      <%= label_tag :email, 'Email address' %>
      <%= email_field_tag :email, nil, placeholder: 'Your email', class: 'form-control' %>
      <p class="help-block">You'll be notified when we reply to your though here.</p>
    </div>

    <div class="form-group">
      <%= label_tag :subject, 'What\'s the problem?' %>
      <%= text_field_tag :subject, nil, placeholder: 'A brief description of the situation', class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= label_tag :content, 'Can you provide any details of your question or issue?' %>
      <%= text_area_tag :content, nil, class: 'form-control' %>
    </div>

    <%= button_tag 'Send', class: 'btn btn-primary pull-right' %>
<% end %>