config/routes.rb
Rails.application.routes.draw do
  post 'messages/create',   to: 'messages#create'
  get  'messages/show/:id', to: 'messages#show'

  get 'tickets/search', to: 'tickets#search'

  get  'access',          to: 'access#login'
  get  'access/sign_up',  to: 'access#sign_up'
  post 'access/sign_up',  to: 'access#create'
  get  'access/index',    to: 'access#login'
  get  'access/login',    to: 'access#login'
  get  'access/logout',   to: 'access#logout'
  post 'access/attempt',  to: 'access#attempt'

  get  'history', to: 'tickets#history_index'
  post 'history', to: 'tickets#history_show'

  get  'submit', to: 'tickets#submit_index'
  post 'submit', to: 'tickets#submit_create'

  get 'intro', to: 'intro#index'

  post 'chat/auth', to: 'chat#auth'

  root to: 'intro#index'

  resources :tickets
  resources :users

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Relay. A support system.</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-default navbar-fixed-top navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= url_for(tickets_path) %>"><%= image_tag 'logo.png', {height: 48, width: 48, class: 'logo'} %></a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <!--<li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>-->
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Tickets <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to 'Add a new ticket', new_ticket_url %></li>
            <li><%= link_to 'Browse all tickets', tickets_url %></li>
          </ul>
        </li>

        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Users <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to 'Add a new user', new_user_url %></li>
            <li><%= link_to 'Browse all users', users_url %></li>
          </ul>
        </li>

      </ul>
      <form class="navbar-form navbar-left" role="search" action="<%= tickets_search_path %>" method="get">
        <div class="form-group">
          <input type="text" class="form-control" name="id" placeholder="Enter a ticket ID">
        </div>
        <button type="submit" class="btn btn-default">Go</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Logged in as <strong><%= session[:fullname] %></strong> <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to 'Edit Profile', edit_user_path(:id => session[:id]) %></li>
            <li><%= link_to 'Logout', access_logout_url %></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<div class="container-fluid">
    <%= yield %>
</div>

</body>
</html>

app/views/layouts/history.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Relay. A support system.</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>


<div class="container-fluid">
  <div class="row">
    <div class="col-lg-6 col-lg-push-3">

      <% unless notice.blank? %>
          <div class="text-center alert alert-<%= flash[:type].present? ? flash[:type] : 'info' %>">
            <%= notice %>
          </div>
      <% end %>

      <%= yield %>
    </div>
  </div>
</div>

</body>
</html>

app/views/layouts/intro.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hi! Welcome to Relay.</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<!-- ain't nobody got time for calling more external stylesheets -->
<style>
    body {
        padding: 0;
    }

    a:hover {
        cursor: pointer;
    }
</style>

<body>

<div class="container-fluid">
  <div class="row">
    <div class="col-lg-6 col-lg-push-3">
      <%= yield %>
    </div>
  </div>
</div>


<script type="text/javascript">
    var show = $('#show-more-info');
    var info = $('#more-info');

    $(document).ready(function() {
        show.on('click', function() {
            console.log('clicked');
            $(this).fadeOut(300, function(){
                console.log('faded out');
                info.removeClass('hidden').hide().fadeIn(300, function() {
                    console.log('faded in');
                });
            });
        });
    });
</script>

</body>
</html>

app/views/layouts/login.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Log into Relay</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container-fluid">
  <%= yield %>
</div>

</body>
</html>